### ISSUE TITLE
zapache/CPULoad not working with Zabbix Agent 2.4.5

### ISSUE THREAD

**Issue by araghav** [lorf/zapache#5]
Hi,

We are using Apache on Ubuntu 14.04. We have installed Zabbix Agent 2.4.5 and using zapache version 1.5 for monitoring Apache performance. While zapache is working fine for all parameters for only CPULoad, it is reporting as ZBX_NOTSUPPORTED. Kindly note that it working fine with Zabbix Agent version 2.4.5 on CentOS 6.4 ad Zabbix Agent 2.2.2 on Ubuntu 14.04.

Could this be a specific issue with Zabbix Agent 2.4.5 on Ubuntu 14.04?

Please help.

Regards,
Ananth

**Comment by lorf** [comment]
Can You please provide output of the following commands on apache server (or equivalent appropriate to your configuration):

    zabbix_get -s localhost -k zapache[CPULoad]
    curl http://localhost/server-status?auto
    sudo -u zabbix bash -x /var/lib/zabbixsrv/externalscripts/zapache CPULoad

**Comment by lorf** [comment]
Also, please check zabbix agent logs, script's stderr goes there.

**Comment by araghav** [comment]
Hi,

The issue is solved now. Actually, it took a very long time, more than 6 hours, to get the CPULoad information and it automatically changed the status from "Not Supported" to "Enabled". Values were so low (0.0003%) - Actually, there was no load on Apache server when I started monitoring. When I activated multiple virtual hosts, proxies & reverse proxies, the values increased and it started to give meaningful readings.

One thing I could not understand, why it took such a long time to capture CPULoad values and reported as Not Supported at the first place?

Regards,
Ananth

**Comment by lorf** [comment]
Sorry, I need more information to debug the issue, such as mentioned commands output with no load on apache server.

**Comment by xiaobao623** [comment]
Hi,Lorf,
I have same issue. My web server no load.
Zabbix 2.4.5 

I put my check log 

[root@pxeserver ~]# netstat -antp|grep 10050
tcp        0      0 127.0.0.1:10050             0.0.0.0:*                   LISTEN      7142/zabbix_agentd  
tcp        0      0 192.168.134.10:10050        0.0.0.0:*                   LISTEN      7142/zabbix_agentd  
tcp        0      0 192.168.134.10:10050        192.168.134.234:33482       TIME_WAIT   -                   
tcp        0      0 192.168.134.10:10050        192.168.134.234:33451       TIME_WAIT   -                   
              
tcp        0      0 192.168.134.10:10050        192.168.134.234:33469       TIME_WAIT   -                   
[root@pxeserver ~]# zabbix_get -s localhost -k zapche[CPULoad]
[root@pxeserver ~]# curl http://localhost/server-status?auto
Total Accesses: 4
Total kBytes: 31
Uptime: 134
ReqPerSec: .0298507
BytesPerSec: 236.896
BytesPerReq: 7936
BusyWorkers: 1
IdleWorkers: 7
Scoreboard: ___W____........................................................................................................................................................................................................................................................
[root@pxeserver ~]# bash -x /var/lib/zabbixsrv/externalscripts/zapache CPULoad
+ zapachever=1.5
+ rval=0
+ value=
+ cache_seconds=60
+ '[' '' ']'
+ TMPDIR=/tmp
+ [[ 1 == 1 ]]
+ STATUS_URL='http://localhost/server-status?auto'
+ CASE_VALUE=CPULoad
+ case "$CASE_VALUE" in
+ umask 077
+ cache_prefix=zapache-0-http___localhost_server-status_auto
+ cache=/tmp/zapache-0-http___localhost_server-status_auto.cache
+ cache_timestamp_check=/tmp/zapache-0-http___localhost_server-status_auto.ts
++ date +%s
+ touch -d @1439966756 /tmp/zapache-0-http___localhost_server-status_auto.ts
+ '[' /tmp/zapache-0-http___localhost_server-status_auto.cache -ot /tmp/zapache-0-http___localhost_server-status_auto.ts ']'
++ which curl
+ curl=/usr/bin/curl
+ '[' /usr/bin/curl ']'
+ fetch_url_cmd='/usr/bin/curl --insecure --silent --location'
+ /usr/bin/curl --insecure --silent --location 'http://localhost/server-status?auto'
+ rval=0
+ '[' 0 '!=' 0 ']'
+ case "$CASE_VALUE" in
+ '[' -s /tmp/zapache-0-http___localhost_server-status_auto.cache ']'
+ case "$CASE_VALUE" in
++ awk '/^CPULoad:/ {print $2}'
+ value=
+ rval=0
+ '[' 0 -eq 0 -a -z '' ']'
+ rval=1
+ '[' 1 -ne 0 ']'
+ echo ZBX_NOTSUPPORTED
ZBX_NOTSUPPORTED
+ echo ''

+ exit 1

**Comment by lorf** [comment]
@xiaobao623 Very thanks for info!
