### ISSUE TITLE
touch: cannot touch: Permission denied

### ISSUE THREAD

**Issue by moses-moore-spafax** [lorf/zapache#6]
The temp file used by zapache is the same filename for every user; thus if I run zapache then anyone else on the same machine will see the 'permission denied'.  This shows up when a normal user or root runs zapache to test it before zabbix_agentd is able to run it for the first time.

The workaround is `rm /tmp/zapache-*` and prevent any users from launching zapache until zabbix_agentd has had a chance to run it (and lock everyone else out).

For a permanent fix, maybe use `$UID` as part of `cache_prefix` ?

**Comment by lorf** [comment]
Good. Thanks!
